system_model:
  N: 6
  M: 8
  T: 100
  snr: 10
  eta: 0.0
  bias: 0.0
  sv_noise_var: 0.0
  field_type: "Far"
  signal_nature: "non-coherent"
  array_form: "mra-6"
  antenna_pattern: false

model:
  model_type: "SparseNet"
  model_params:
    tau: 8
    diff_method: "esprit"

training:
  samples_size: 4096
  train_test_ratio: 0.1
  epochs: 150
  batch_size: 256
  optimizer: "Adam"
  learning_rate: 0.001
  weight_decay: 1e-9
  step_size: 50
  gamma: 0.5
  scheduler: "StepLR"
  training_objective: "angle"
  criterion: "rmspe"
  balance_factor: 1.0
  true_doa_train: null
  true_range_train: null
  true_doa_test: null
  true_range_test: null

evaluation:
  criterion: "rmspe"
  balance_factor: 1.0
  models:
    SparseNet:
      tau: 8
      diff_method: "esprit"
  augmented_methods: []
  subspace_methods: ["esprit"]

commands:
  create_data: true
  save_dataset: true
  train_model: true
  save_model: true
  evaluate_mode: true
  plot_results: true
  save_plots: false

# Optional scenario sweep:
# scenario:
#   eta: [0.01, 0.02, 0.03]